language: ruby
bundler_args: --without guard metrics
script: "bundle exec rake spec"
rvm:
  - 1.9.2
  - 1.9.3
  #- jruby-19mode # JRuby in 1.9 mode, no cextension support on travis
  - rbx-19mode
notifications:
  irc:
    channels:
      - irc.freenode.org#rom-rb
    on_success: never
    on_failure: change
