language: ruby
bundler_args: --without guard metrics
script: "bundle exec rake spec"
rvm:
  #- 1.8.7
  - 1.9.2
  - 1.9.3
  #- jruby-18mode # JRuby in 1.8 mode, no cextension support on travis
  #- jruby-19mode # JRuby in 1.9 mode, no cextension support on travis
  #- rbx-18mode
  - rbx-19mode
notifications:
  irc: "irc.freenode.org#datamapper"
  email:
    - mbj@seonic.net
